"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import LinkButton from "~/components/buttons/link-button";
import { Button } from "~/components/ui/button";

const DownloadDraweek = () => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-assignment
  const [promptEvent, setPromptEvent] = useState<any>(null);

  useEffect(() => {
    const handleBeforeInstallPrompt = (event: Event) => {
      event.preventDefault();
      setPromptEvent(event);
    };

    window.addEventListener("beforeinstallprompt", handleBeforeInstallPrompt);

    return () => {
      window.removeEventListener(
        "beforeinstallprompt",
        handleBeforeInstallPrompt,
      );
    };
  }, []);

  const handleDownload = () => {
    if (promptEvent) {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
      promptEvent.prompt();
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
      promptEvent.userChoice.then((choiceResult: { outcome: string }) => {
        if (choiceResult.outcome === "accepted") {
          toast.success("Thank you for downloading Drawdle");
        } else {
          toast.message("Please reconsider downloading Drawdle in the future.");
        }
        setPromptEvent(null);
      });
    }
  };

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      {!window.matchMedia("(display-mode: standalone)").matches ? (
        <>
          <h1 className="text-center text-2xl font-semibold text-foreground">
            Download Draweek
          </h1>
          <div className=" text-center text-gray-300">
            {
              "Discover the power of clicking the download button! Download now and level up your life with Draweek. Gain access to the newest features and most importantly, you won't have to see this message again."
            }
          </div>
          <Button onClick={handleDownload}>Download</Button>
        </>
      ) : (
        <>
          <h1 className="text-center text-2xl font-semibold text-foreground">
            HELP
          </h1>
          <div className=" text-center text-gray-300">
            {
              "Feel free to recommend what should be here. Maybe another image or perhaps some sort of monthly event thing."
            }
          </div>
          <div className=" text-center text-gray-300">
            {
              "It also would be useful if you could think of some words ideally nouns to add to the list of autogenerated ideas. I recommend using any json editor to help with formatting "
            }
            <Link
              className="text-gray-500 hover:text-gray-200"
              href="https://jsoneditoronline.org/"
            >
              {"even an online one."}
            </Link>
          </div>
          <LinkButton
            text="Have a look at the current list"
            link="/drawableWords.json"
            message={null}
          ></LinkButton>
        </>
      )}
    </div>
  );
};

export default DownloadDraweek;
