import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Drawdle",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
function TopNav() {
  return (
    <nav className="flex justify-between items-center border-b font-semibold text-xl p-4 bg-gray-800 text-white">
      <div>Drawdle</div>
      <div>Sign in</div>
    </nav>
  );

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex-col gap-4">
        <TopNav />
        {children}
      </body>
    </html>
  );
}
