name: Weekly Draweek

on:
  schedule:
    - cron: "58 21 * * 0"

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Curl API request
        run: curl -X POST https://drawdle.art/api/draweek/
