name: Weekly Draweek

on:
  schedule:
    - cron: "58 21 * * 0"

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Curl API request with debugging
        run: |
          curl -L -X POST -H "Content-Type: application/json" https://drawdle.art/api/draweek/ -o response.txt -w "%{http_code}"
          echo "Response:"
          cat response.txt
